version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # ignore devDependencies if you prefer to handle them manually
    # ignore:
    #   - dependency-type: "dev"
