name: Manual GitHub Pages deploy (build → publish)

on:
  workflow_dispatch: {}

permissions:
  actions: read
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-publish:
    name: Build and publish to GitHub Pages
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: 'Vite: build dist'
        run: npx vite build

      - name: 'Deploy to gh-pages branch (push built files)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          SHA=$(git rev-parse --short HEAD || echo "local")
          # prepare a temp directory with the built site
          TMPDIR=$(mktemp -d)
          cp -r ./dist/. "$TMPDIR/" || true
          cd "$TMPDIR"
          # initialize a repo and push to gh-pages branch
          git init
          git checkout -b gh-pages
          git add --all
          git commit -m "Deploy ${SHA} to gh-pages" || true
          # push using the GITHUB_TOKEN
          git push --force "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" gh-pages:gh-pages
