name: Manual GitHub Pages deploy (build → publish)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: 'Vite: build dist'
        run: npx vite build

      - name: 'Info: prepare to upload artifact'
        run: echo "Uploading ./dist as artifact 'github-pages'"

      - name: Upload dist artifact (github-pages)
        run: |
          echo "Packaging ./dist into a single gzip'd tar for Pages"
          # create a gzip compressed tarball containing the contents of ./dist
          tar -czf github-pages.tar.gz -C ./dist .

      - name: Upload artifact (github-pages)
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: github-pages.tar.gz

  publish:
    name: Publish to gh-pages
    needs: build
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: 'Info: preparing download'
        run: echo "Downloading artifact 'github-pages' into ./dist for publishing"

      - name: 'Deploy artifact to GitHub Pages (actions/deploy-pages)'
        uses: actions/deploy-pages@v1
