name: Manual GitHub Pages deploy

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build (dist)
        run: npx vite build

      - name: Upload artifact for Pages (upload-artifact v4 사용)
        # deploy-pages 단계가 찾는 아티팩트 이름은 'github-pages'입니다. 동일한 이름으로 업로드합니다.
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Download pages artifact
        # upload-artifact로 업로드한 'github-pages' 아티팩트를 받아 배포에 사용
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist

      - name: Deploy to gh-pages branch (peaceiris)
        # deploy-pages action의 artifact 요구사항 문제를 우회하기 위해
        # dist를 gh-pages 브랜치로 직접 푸시합니다.
        # 주의: GitHub Pages 설정에서 Source를 'gh-pages branch'로 변경해야 합니다.
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          publish_branch: gh-pages
          # GITHUB_TOKEN 권한으로 푸시
          github_token: ${{ secrets.GITHUB_TOKEN }}
